# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '二级列表' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod "AFNetworking"
pod "JSONKit"
  # Pods for 二级列表

  target '二级列表Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '二级列表UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
